name: Create kpa-marp-pandoc container image

env:
  REGISTRY_GHCR: ghcr.io/mmul-it
  REGISTRY_QUAY: quay.io/mmul
  CONTAINER_NAME: kpa-marp-pandoc

on: [push]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check whether github.ref_type is branch or tag
      run: if [ "${{ github.ref_type }}" == 'branch' ];
            then
             echo "CONTAINER_VERSION=$(echo ${{ github.sha }} | cut -c 1-12)" >> ${GITHUB_ENV};
            else
             echo "CONTAINER_VERSION=$(echo ${{ github.ref_name }})" >> ${GITHUB_ENV};
           fi
    - name: Build the container image
      run: docker build .
             --file Dockerfile
             --tag ${REGISTRY_GHCR}/${CONTAINER_NAME}:${CONTAINER_VERSION}
             --tag ${REGISTRY_GHCR}/${CONTAINER_NAME}:latest
             --tag ${REGISTRY_QUAY}/${CONTAINER_NAME}:${CONTAINER_VERSION}
             --tag ${REGISTRY_QUAY}/${CONTAINER_NAME}:latest
    - name: Login into the GitHub Container Registry
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ${REGISTRY_GHCR} --username "${{ vars.GHCR_USER }}" --password-stdin
    - name: Login into the Quay Container Registry
      run: echo "${{ secrets.QUAY_ROBOT_TOKEN }}" | docker login ${REGISTRY_QUAY} --username "${{ vars.QUAY_ROBOT_NAME }}" --password-stdin
    - name: Push the image into the GitHub Container Registry
      run: docker push --all-tags ${REGISTRY_GHCR}/${CONTAINER_NAME}
    - name: Push the image into the Quay Container Registry
      run: docker push --all-tags ${REGISTRY_QUAY}/${CONTAINER_NAME}
