name: Create kpa-marp-pandoc container image

env:
  REGISTRY_NAME: ghcr.io
  CONTAINER_NAME: mmul-it/kpa-marp-pandoc
  CONTAINER_VERSION: latest

on: [push]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the container image
      run: docker build . --file Dockerfile --tag ${REGISTRY_NAME}/${CONTAINER_NAME}:${CONTAINER_VERSION}
    - name: Login into the container registry
      run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ vars.GHCR_USER }} --password-stdin
    - name: Push the image into the container registry
      run: docker push ${REGISTRY_NAME}/${CONTAINER_NAME}:${CONTAINER_VERSION}
