name: Create kpa-marp-pandoc container image

env:
  REGISTRY_NAME: ghcr.io
  CONTAINER_NAME: mmul-it/kpa-marp-pandoc

on: [push]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check whether github.ref_type is branch or tag
      run: if [ "${{ github.ref_type }}" == 'branch' ];
            then
             echo "CONTAINER_VERSION=$(echo ${{ github.sha }} | cut -c 1-12)" >> ${GITHUB_ENV};
            else
             echo "CONTAINER_VERSION=$(echo ${{ github.ref_name }})" >> ${GITHUB_ENV};
           fi
    - name: Build the container image
      run: docker build .
             --file Dockerfile
             --tag ${REGISTRY_NAME}/${CONTAINER_NAME}:${CONTAINER_VERSION}
             --tag ${REGISTRY_NAME}/${CONTAINER_NAME}:latest
    - name: Login into the container registry
      run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ vars.GHCR_USER }} --password-stdin
    - name: Push the image into the container registry
      run: docker push --all-tags ${REGISTRY_NAME}/${CONTAINER_NAME}
