name: Create kpa-marp-pandoc container image

on: [push]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to ghcr
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ vars.GHCR_USER }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Login to quay
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: ${{ vars.QUAY_ROBOT_NAME }}
        password: ${{ secrets.QUAY_ROBOT_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        # Check https://github.com/docker/build-push-action/issues/820
        provenance: false
        platforms: linux/amd64,linux/arm64
        tags: |
           ghcr.io/mmul-it/kpa-marp-pandoc:latest
           ghcr.io/mmul-it/kpa-marp-pandoc:${{ github.ref_name }}
           quay.io/mmul/kpa-marp-pandoc:latest
           quay.io/mmul/kpa-marp-pandoc:${{ github.ref_name }}
